development:
  adapter: postgresql
  encoding: unicode
  database: acts_as_talented_dev
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: acts_as_talented_test
  pool: 5
  host: localhost
  username: postgres
  password: postgres
  port: 5432
  min_messages: warning
